# Use a lightweight Java base image
FROM eclipse-temurin:17-jdk-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file built by Maven or Gradle into the container
COPY target/healthify-gateway-0.0.1-SNAPSHOT.jar /app/healthify-gateway-0.0.1-SNAPSHOT.jar

# Expose the port your application listens on (default Spring Boot port)
EXPOSE 8080

# Set environment variables for Kafka (optional)
ENV SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092

# Define the entry point to run the Spring Boot application
ENTRYPOINT ["java", "-jar", "/app/healthify-gateway-0.0.1-SNAPSHOT.jar"]
